project:
  type: website
  output-dir: docs

website:
  title: "Arif Narváez - Analisis de Algoritmos"
  navbar:
    left:
      - href: about.qmd
        text: Sobre Mí
      - href: unidad1.qmd
        text: Unidad 1
      - href: unidad2.qmd
        text: Unidad 2
      - href: unidad3.qmd
        text: Unidad 3
      - href: unidad4.qmd
        text: Unidad 4
      - href: unidad5.qmd
        text: Unidad 5
      - href: changelog.qmd
        text: Listado de modificaciones
  sidebar:
    left: 
      - contents
    right: 
      - toc
  page-footer: 
    center: "Copyright © 2025 Arif Narváez"

format:
  html:
    css: styles.css
    theme: 
      light: cosmo
    variables:
      primary: "#2a7f62"
      dark: "#1a535c"
      light: "#f7fff7"
    toc: true
    toc-depth: 3